BlisTimer/Controllers/TimeLogController.cs
using System.Net;
using BlisTimer.Models;
using BlisTimer.Data;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace BlisTimer.Controllers
{
    public class TimeLogController : Controller
    {
        private readonly TimerDbContext _context;
        private readonly ILogger<TimeLogController> _logger;
        private readonly ApiDatabaseHandler _databasehandler;

        public TimeLogController(TimerDbContext context, ILogger<TimeLogController> logger, ApiDatabaseHandler databaseHandler)
        {
            _logger = logger;
            _context = context;
            _databasehandler = databaseHandler;
        }
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var timeLogs = _context.TimeLogs
                .Include(_ => _.Activity.Project)
                .Include(_ => _.HourType)
                .Where(_ => _.EmployeeId == HttpContext.User.Claims.ToList()[0].Value)
                .ToList()
                .Where(_ => (!_.Deleted && !_.Submitted)).OrderByDescending(_ => _.EndTime).ToList();

            var totalWorkedHours = timeLogs.Select(_ => _.EndTime - _.StartTime).Sum(_ => _.TotalHours);
            var time = TimeSpan.FromHours(totalWorkedHours);
            ViewBag.totalTime = $"{time.TotalHours.ToString("0#")}:{time.Minutes.ToString("0#")}:{time.Seconds.ToString("0#")}";

            return View(timeLogs);
        }

        
        [Authorize]
        public async Task<RedirectToActionResult> Delete(string id)
        {
            var employeeId = HttpContext.User.Claims.ToList()[0].Value;

            TimeLog timelog;
            try {
                timelog = await _context.TimeLogs.Where(_ => _.Id == id && _.EmployeeId == employeeId).SingleAsync();
            }
            catch (Exception e) {
                _logger.LogError(e, "Error while deleting timelog");
                return RedirectToAction("Index");
            }
            
            timelog.Deleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> Edit(string id)
        {
            var employeeId = HttpContext.User.Claims.ToList()[0].Value;
            var log = await _context.TimeLogs.SingleAsync(_ => _.Id == id && _.EmployeeId == employeeId);

            try
            {
                ViewBag.log = log;
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Error while editing timelog");
                return RedirectToAction("Index");
            }
            
            ViewBag.min = log.StartTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
            ViewBag.start = log.StartTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
            ViewBag.end = log.EndTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
            ViewBag.cet = log.EndTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
            ViewBag.max = log.EndTime.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
            
            
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(TimeLogAdd timeForm, string id)
        {
            if (timeForm.StartTime > timeForm.EndTime)
                return Redirect("/Login?error=999");
            
            var employeeId = HttpContext.User.Claims.ToList()[0].Value;
            
            TimeLog log;
            try {
                log = await _context.TimeLogs.Where(_ => _.Id == id && _.EmployeeId == employeeId).SingleAsync();
            }
            catch (Exception e) {
                _logger.LogError("User tried to edit a time-log that does not belong to them or that does not exist");
                return Redirect("/TimeLog");
            }

            log.StartTime = timeForm.StartTime.ToUniversalTime();
            log.EndTime = timeForm.EndTime.ToUniversalTime();
            
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SumbitTimelog(int timeModified)
        {
            var employeeId = HttpContext.User.Claims.ToList()[0].Value;
            
            if (!_context.RunningTimers.Any(_ => _.EmployeeId == employeeId))
                return BadRequest("There aren't any active timers running for the employee");

            var runningTimer = _context.RunningTimers.FirstOrDefault(_ => _.EmployeeId == employeeId);

            if (runningTimer!.StartTime.AddSeconds(timeModified * -1) > DateTime.Now.ToUniversalTime())
                return BadRequest("Timer cannot be modified to a negative number");

            await _context.TimeLogs.AddAsync(new TimeLog()
            {
                Id = Guid.NewGuid().ToString(),
                StartTime = runningTimer.StartTime.AddSeconds(timeModified * -1),
                EndTime = DateTime.Now.ToUniversalTime(),
                ActivityId = HttpContext.Session.GetString("ActivityId")!,
                HourTypeId = HttpContext.Session.GetString("HourTypeId")!,
                ProjectId = HttpContext.Session.GetString("ProjectId")!,
                EmployeeId = employeeId!,
            });

            _context.RunningTimers.Remove(runningTimer);

            await _context.SaveChangesAsync();
            
            return Ok();
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddRunningTimer(int time)
        {
            if (time < 0)
                return BadRequest("Timer cannot start with a negative number");
                
            if (_context.RunningTimers.Any(_ => _.EmployeeId == HttpContext.User.Claims.ToList()[0].Value))
            {
                Console.WriteLine("There is already a running timer");
                return BadRequest("There is already a running timer for the employee");
            }
            
            try
            {
                await _context.RunningTimers.AddAsync(new()
                {
                    Id = Guid.NewGuid().ToString(),
                    StartTime = DateTime.Now.ToUniversalTime().AddSeconds(time * -1),
                    EmployeeId = HttpContext.User.Claims.ToList()[0].Value!,
                    ActivityId = HttpContext.Session.GetString("ActivityId")!,
                    HourTypeId = HttpContext.Session.GetString("HourTypeId")!,
                });
                await _context.SaveChangesAsync();
                return Ok();
            }
            catch (Exception err)
            {
                _logger.LogError("Couldn't add running timer to database with error: " + err.Message);
                return BadRequest("There was probably already a timer running for this employee");
            }
            
        }

        public async Task<IActionResult> ChangeRunningTimer(int time)
        {
            try
            {
                var employeeId = HttpContext.User.Claims.ToList()[0].Value;

                var timer = _context.RunningTimers.FirstOrDefault(_ => _.EmployeeId == employeeId);
                
                var startTime = timer.StartTime.ToUniversalTime();
                
                if (startTime.AddSeconds(time * -1) > DateTime.Now.ToUniversalTime())
                    return BadRequest("Timer cannot go to a negative number");
                
                // Time has to be converted to negative, because we want to subtract the added minutes from the start date
                timer.StartTime = startTime.AddSeconds(time * -1);
                

                await _context.SaveChangesAsync();
                return Ok();
            }
            catch (Exception err)
            {
                _logger.LogError("Couldn't add running timer to database with error: " + err.Message);
                return BadRequest("There was probably already a timer running for this employee");
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PostHoursToSimplicate()
        {
            if (HttpContext.Session.GetString("hoursBeingSubmitted") == "true")
                return BadRequest("There are already hours being submitted");
            
            var hoursToSubmit = _context.TimeLogs
                .Where(_ => !_.Submitted && !_.Deleted)
                .Include(_ => _.Activity)
                .Include(_ => _.HourType)
                .Include(_ => _.Employee)
                .ToList()
                .Where(_ => _.EmployeeId == HttpContext.User.Claims.ToList()[0].Value!).ToList();
            
            if (hoursToSubmit.Count == 0)
                return BadRequest("There are no hours to submit");
            
            HttpContext.Session.SetString("hoursBeingSubmitted", "true");

            try
            {
                var failedSubmissions = await _databasehandler.SubmitHoursToSimplicate(hoursToSubmit);
                
                var successfullySubmittedHours = hoursToSubmit.Where(_ => !failedSubmissions.Contains(_)).ToList();
                
                foreach (var hour in successfullySubmittedHours)
                    hour.Submitted = true;
                
                await _context.SaveChangesAsync();

                if (failedSubmissions.Any())
                {
                    HttpContext.Session.SetString("hoursBeingSubmitted", "false");
                    return BadRequest(300);
                }
            }
            catch (Exception e)
            {
                HttpContext.Session.SetString("hoursBeingSubmitted", "false");
                _logger.LogError("Error while submitting hours to simplicate: " + e.Message);
                return BadRequest("Something went wrong while connecting to the simplicate API");
            }

BlisTimer/Views/TimeLog/Edit.cshtml
@model Domain.Models.TimeLog

@{
    ViewData["Title"] = "Edit Timelog Page";
}

<style>
    #inputBox input {
        width: 170px;
        padding-left: 20px;
        border: none;
        border-radius: 1em;
        margin: 0 2%;
    }
</style>

<div class="main">
    <div id="container">
        <div id="formBox">
            <form asp-controller="TimeLog" method="post">
                <div id="labelBox">
                    <label>Start time:</label>
                    <label>End time:</label>
                </div>
                <div id="inputBox">
                    <input id="st" type="datetime-local" asp-for="StartTime" max="@ViewBag.cet" value="@ViewBag.start" required />
                    <input id="et" type="datetime-local" asp-for="EndTime" min="@ViewBag.min" max="@ViewBag.max" value="@ViewBag.end" required />
                </div>
                <div id="submitBox">
                    <input type="submit" value="Save changes">
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    //start date/time changes -> end Date/time change aswell
    document.getElementById("st").addEventListener("change", function(){
        document.getElementById("et").min = document.getElementById("st").value;
    });

    //end date/time changes -> start Date/time change aswell
    document.getElementById("et").addEventListener("change", function () {
        document.getElementById("st").max = document.getElementById("et").value;
    });
</script>

BlisTimer/Views/TimeLog/index.cshtml
@using System.Globalization
@model List<Domain.Models.TimeLog>

@{
    ViewData["Title"] = "Overview Page";
}

<script>
    function submitHours() {
        $.ajax({
          type: "POST",
          url: "/TimeLog/PostHoursToSimplicate",
            data: "{}",
            success: function (result) {
              location.reload();
            },
            error: function (result) {
              alert("An error occured while sending the hours");
              setTimeout(function () {
                location.reload();
              }, 3000);
            }
        })
    }
</script>

<style>
    #buttons{
        display: inline-flex;
    }

    #submitButton, input[type="button"] {
        color: #ffffff;
        border: 1px solid #ddd;
        border-radius: 5px;
        margin: 0 2px;
        height: 40px;
    }
    #submitButton{
        display: flex;
        margin: 0 2px;
        width: 130px;
        justify-content: center;
        align-items: center;
    }
    input[type="button"]{
        padding: 8px 16px;
        text-decoration: none;
    }
    input[type="button"]:not(.active){
        background-color: transparent;
    }

    .active{
        background-color: var(--blis-cyan);
        color: #fff;
    }

    input[type="button"]:hover:not(.active){
        background-color: #ddd;
    }

    #controlsContainer, #totalTimeContainer {
        display: inline-flex;
    }
    #controlsContainer{
        margin-top: 2vh;
        width: 1100px;
        justify-content: space-between;
    }
    #totalTimeContainer{
        /*transform: translate(0, -43px);
        width: 100%;
        justify-content: center;*/
    }
    #submitButton:hover{
        background-color: #ddd;
        cursor: pointer;
    }

    /* div for edit and delete button */
    #submitContainer {
        display: inline-flex;
    }

    #handleButtons{
        display: flex;
    }
    a.editButton img{
        width: 32px;
        filter: invert(75%) sepia(19%) saturate(2426%) hue-rotate(360deg) brightness(120%) contrast(105%);
    }
    #deleteButton img{
        width: 32px;
        filter: invert(24%) sepia(82%) saturate(4339%) brightness(86%) contrast(141%);
    }
    
    #table-container{
        height: calc(100vh);
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    @@media (max-width: 1265px)
    {
        #table-container{
            height: calc(100vh - 50px);
            margin-top: 0;
        }
    }

    @@media (max-width: 1100px)
    {
        #controlsContainer {
            width: 95%;
        }
    }

    @@media (max-width: 850px)
    {
        #table-container{
            height: calc(100vh - 50px);
            display: block;
        }
    
        html{
            overflow: auto;
        }
        tr#header{
            display: none;
        }
        td{
            display: block;
        }
        td:first-child{
            background-color: var(--blis-cyan);
            text-align: center;
            color: black;
            font-weight: 600;
        }
        td:nth-child(2)::before{
            content: "Activity: ";
        }
        td:nth-child(3)::before{
             content: "Start time: ";
        }
        td:nth-child(4)::before{
            content: "End time: ";
        }
        td:nth-child(5)::before{
            content: "Hours Worked: ";
        }
        td:nth-child(6)::before{
            content: "Hourtype: ";
        }

        #controlsContainer {
            width: 96%;
            justify-content: space-between;
            margin: 2vh 2vw 0 2vw;
        }
        input.pageButtons, input.active{
            display: none;
        }

        #totalTimeContainer {
            transform: translate(0, -5px);
        }
    }
    @@media (max-width: 515px)
    {
        #controlsContainer {
            margin: 6vh 2vw 2vh 2vw;
        }
        #totalTimeContainer {
            position: absolute;
            transform: translate(-8px, -45px);
            justify-content: center;
            display: flex;
            width: 100%;
        }
    }
</style>

<div class="main">
    @if (Model.Count == 0)
    {
        <div id="noRecordsContainer">
            <h2>Whoops, no existing records</h2>
        </div>
    }
    else
    {
        <div id="table-container">
            <div id="time-table">
                <table id="logTable">
                    <thead>
                    <tr id="header">
                        <th>Project</th>
                        <th>Activity</th>
                        <th>StartTime</th>
                        <th>EndTime</th>
                        <th>Hours Worked</th>
                        <th>HourType</th>
                        <th>Handle</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var timelog in Model)
                    {
                        var nlCulture = new CultureInfo("nl-NL");
                        <tr>
                            <td>@timelog.Activity.Project.Name</td>
                            <td>@timelog.Activity.Name</td>
                            <td>@timelog.StartTime.ToLocalTime()</td>
                            <td>@timelog.EndTime.ToLocalTime()</td>
                            <td>
                                @{var workedHours = timelog.EndTime - timelog.StartTime;}
                                @workedHours.TotalHours.ToString("0#"):@workedHours.Minutes.ToString("0#")
                            </td>
                            <td>@timelog.HourType.Label</td>
                            <td>
                                <div id="handleButtons">
                                    <a class="editButton" asp-controller="TimeLog" asp-action="Edit" asp-route-id="@timelog.Id">
                                        <img src="~/icons/edit.svg" alt="Icon resembling editing something"/>
                                    </a>
                                    <a id="deleteButton" onclick="toggleDeleteTimePopup('@timelog.Id')">
                                        <img src="~/icons/delete.svg" alt="A red cross resembling deleting"/>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <div id="controlsContainer">
                <div id="submitContainer">
                    <a id="submitButton" onclick="toggleSubmitHoursPopup()">Submit hours</a>
                </div>
                <div id="totalTimeContainer">
                    <p>Total time worked: @ViewBag.totalTime</p>
                </div>
            </div>
        </div>
    }
</div>

<div id="popup-backdrop" style="display: none">
    <div id="popup-delete" style="display: none">
        <p>Are you sure you want to delete this hour?</p>
        <div class="button-container">
            <a onclick="toggleDeleteTimePopup('')">Cancel</a>
            <a href="">Confirm</a>
        </div>
    </div>
    <div id="popup-submit" style="display: none">
        <p>Are you sure you want to submit your hours?</p>
        <div class="button-container">
            <a onclick="toggleSubmitHoursPopup()">Cancel</a>
            <a onclick="submitHours()">Confirm</a>
        </div>
    </div>
</div>

<script>
    
    const toggleBlurBackground = () => {
        var popup_backdrop = document.getElementById("popup-backdrop");
        if (popup_backdrop.style.display === "none") {
            popup_backdrop.style.display = "flex";
        } else {
            popup_backdrop.style.display = "none";
        }
    }
    
    const toggleDeleteTimePopup = (id) => {
        var popup_delete = document.getElementById("popup-delete");
        
        if (popup_delete.style.display === "none") {
            toggleBlurBackground();
            popup_delete.children[1].children[1].setAttribute("href", "/TimeLog/Delete/" + id);
            popup_delete.style.display = "flex";
        } else {
            popup_delete.style.display = "none";
            popup_delete.children[1].children[1].setAttribute("href", "");
            toggleBlurBackground();
        }
    }
    
    const toggleSubmitHoursPopup = () => {
        var popup_submit = document.getElementById("popup-submit");
        
        if (popup_submit.style.display === "none") {
            toggleBlurBackground();
            popup_submit.style.display = "flex";
        } else {
            popup_submit.style.display = "none";
            toggleBlurBackground();
        }
    }

    var $table = document.getElementById("logTable"),
        $div = document.getElementById("totalTimeContainer"),
        $rowsPerPage = 4,
        $rowCount = $table.rows.length,
        $firstRow = $table.rows[0].firstElementChild.tagName,
        // Check if table has a head row
        $hasHead = ($firstRow === "TH"),
        // Array to hold each row
        $tr = [],
        // Count vars, counts from 2nd row if first is "th"
        $i, $ii, $j = ($hasHead) ? 1 : 0,
        // Holds first row if it has "th", nothing "td"
        $th = ($hasHead ? $table.rows[(0)].outerHTML : "");
    if ($rowCount % $rowsPerPage <= 1) {
        $pageCount = Math.floor($rowCount / $rowsPerPage);
    } else {
        $pageCount = Math.ceil($rowCount / $rowsPerPage);
    }
    // Does something if we have more than 1 page
    if ($pageCount > 1) {
        // Assigns each table row to table
        for ($i = $j, $ii = 0; $i < $rowCount; $i++, $ii++)
            $tr[$ii] = $table.rows[$i].outerHTML;
        // Div block for the buttons
        $div.insertAdjacentHTML("afterend", "<div id='buttons'></div");
        // Set default page (first amount of rows)
        sort(1);
    }

    function sort($selectedPage) {
        // Rows holds group rows, startpoint is first row on each page
        var $rows = $th, $startPoint = (($rowsPerPage * $selectedPage) - $rowsPerPage);
        for ($i = $startPoint; $i < ($startPoint + $rowsPerPage) && $i < $tr.length; $i++)
            $rows += $tr[$i];

        $table.innerHTML = $rows;
        // Creates pagination buttons
        document.getElementById("buttons").innerHTML = pageButtons($pageCount, $selectedPage);
        document.getElementById("id" + $selectedPage).setAttribute("class", "active");
    }

    function pageButtons($pageCount, $currentPage) {
        // Disables buttons on first and last page
        var $prevDis = ($currentPage == 1) ? "disabled" : "",
            $nextDis = ($currentPage == $pageCount) ? "disabled" : "",
            
            // Holds the buttons 
            $buttons = "<input type='button' id='prevButton' value='<< Prev' onclick='sort(" + ($currentPage - 1) + ")' " + $prevDis + ">";
        $buttons += "<input type='button' id='nextButton' value='Next >>' onclick='sort(" + ($currentPage + 1) + ")' " + $nextDis + ">";
        return $buttons;
    }
</script>